routes/web.php
<?php

use App\Http\Controllers\Dashboard\NotificationController;
use App\Models\Advertisement;
use App\Models\Attribute;
use App\Models\Cart;
use App\Models\Category;
use App\Models\Chat;
use App\Models\Desire;
use App\Models\Order;
use App\Models\Subattribute;
use Carbon\Carbon;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Login to Dashboard
// Route::get('/', 'Dashboard\AuthController@index')->name('home');


Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']], function () {

    //IF Admin Not Auth Return to login
    // Route::get('/dashboard', function () {
    //     return view('dashboard.index');
    // })->name('pagee')->middleware('adminauth:admin');

    // Website routes
    // Route::group(['namespace' => 'Site'], function () {
    //     Route::get('/', 'SiteController@index');
    // });



    // Clear application cache:
    Route::get('/clear-cache', function() {
        \Artisan::call('optimize:clear');
            // \Artisan::call('cache:clear');
        return 'Application cache has been cleared';
    });

    //site route
    //Route::get('/', 'Site\SiteController@index');
    Route::get('/',function(){
        return '404 Not Found!';
    });

    // Dashboard routes
    Route::group(['prefix' => 'dashboard', 'namespace' => 'Dashboard'], function () {
        Route::get('/', 'DashboardController@index')->name('pagee')->middleware('adminauth:admin');
        //Login process
        Route::get('/login', 'AuthController@login')->name('admin.login');
        Route::post('/do-login', 'AuthController@doLogin')->name('admin.doLogin');

        Route::name('admin.')->middleware('adminauth:admin')->group(function () {
            //Logout proccess
            Route::get('/logout', 'AuthController@logout')->name('logout');

            //Admin Routes
            Route::resource('users', 'AdminController')->except(['show']);

            // Profile
            Route::get('profile', 'ProfileController@profile')->name('profiles');
            Route::get('profile/edit', 'ProfileController@editProfile')->name('profiles.edit');
            Route::put('profile/update', 'ProfileController@updateProfile')->name('profiles.update');
            Route::get('profile/change_password', 'ProfileController@changePassword')->name('profiles.change_password');
            Route::put('profile/change_password', 'ProfileController@change_password_method')->name('profiles.change_password_method');

            //Customers routes
            Route::resource('customer', 'CustomersController');
            Route::get('customer-excel', 'CustomersController@customersPrintExcel')->name('customer.index.excel');


            //Merchant routes
            Route::resource('merchant', 'MerchantController');
            // Route::get('merchant/active/{id}', 'MerchantController@changeStatus')->name('merchant.active');addComments
            Route::post('merchant/addComments', 'MerchantController@addComments')->name('merchant.addComments');
            Route::get('merchant/active/{id}', 'MerchantController@changeStatus')->name('merchant.active');
            Route::get('merchant/dependence/{id}', 'MerchantController@changeDependence')->name('merchant.dependence');
            Route::get('merchant/changeViewRate/{id}', 'MerchantController@changeViewRate')->name('merchant.changeViewRate');
            Route::get('merchant-excel', 'MerchantController@merchantsPrintExcel')->name('merchant.index.excel');


            // Country routes
            Route::resource('countries', CountryController::class);

            // Governorates routes
            Route::resource('countries/{country}/governorates', GovernorateController::class);

            // districts routes
            Route::resource('countries/{country}/governorates/{governorate}/districts', DistrictController::class);

            // Categories routes
            Route::resource('categories', CategoryController::class);

            //Subcategories routes
            Route::resource('categories/{cat}/subcategories', SubcategoryController::class);

            // Attributes routes
            Route::resource('categories/{cat}/subcategories/{subcat}/attributes', AttributeController::class);
            Route::post('categories/{cat}/subcategories/{subcat}/attributes/save', 'AttributeController@createSub')->name('subattributes.save');
            Route::post('categories/{cat}/subcategories/{subcat}/attributes/delete/{id}', 'AttributeController@deleteSub')->name('subattributes.delete');

            //Advertisements
            Route::resource('advertisements', AdvertisementController::class);
            Route::get('fees-expiration' , 'AdvertisementController@getFeesExpiration')->name('fees-expiration.index');
            Route::get('advertisements/popular/{id}', 'AdvertisementController@changeStatusPopular')->name('advertisements.popular');

            Route::post('advertisements/fees-expiration' , 'AdvertisementController@updateFeesExpiration')->name('fees-expiration.update');
            Route::resource('advertisement-types' , AdvertisementTypeController::class);

            //special advertisements
            Route::resource('special-advertisements' , SpecialAdvertisementController::class);

            //Subscriptions
            Route::resource('subscriptions', SubscriptionController::class);

            //Funds
            Route::get('financing_request', 'FundController@financingRequest')->name('financing_request');
            Route::resource('funds', FundController::class);


            Route::get('report', 'SettingController@report')->name('report.index');
            Route::get('report-excel', 'SettingController@reportPrintExcel')->name('report.index.excel');

            // Setting
            Route::resource('slider', 'SliderController');
            Route::post('ajaxLoad', 'SliderController@ajaxLoad')->name('ajaxLoad');

            Route::get('feedbacks','SettingController@feedback')->name('setting.feedback');
            Route::get('form_contact_us','SettingController@formContactUs')->name('setting.form_contact_us');

            Route::get('setting/banner', 'SettingController@banner')->name('setting.banner');
            Route::put('setting/banner/{id}/update', 'SettingController@editBanner')->name('setting.banner.update');

            Route::get('setting/banner/{id}/delete', 'SettingController@deleteBanner')->name('setting.banner.delete');

            Route::get('setting/contact-us', 'SettingController@contactUs')->name('setting.contact-us');
            Route::put('setting/contact-us/{id}/update', 'SettingController@editContactUs')->name('setting.contact-us.update');

            Route::get('setting/terms', 'SettingController@terms')->name('setting.terms');
            Route::put('setting/terms/{id}/update', 'SettingController@editTerms')->name('setting.terms.update');

            Route::get('setting/about', 'SettingController@about')->name('setting.about');
            Route::put('setting/about/{id}/update', 'SettingController@editAbout')->name('setting.about.update');

            Route::get('setting/delivery-tax', 'SettingController@deliveryCostAndTax')->name('setting.delivery-tax');
            Route::post('setting/delivery-tax', 'SettingController@updateDeliveryCostAndTax')->name('setting.delivery-tax.update');

            //Notifications
            Route::get('notifications','NotificationController@index')->name('notifications.index');
            Route::post('notifications','NotificationController@send')->name('notifications.send');

            //coupons
            Route::resource('coupons','CouponController');
        });
    });
});
Route::get('test', function () {

});

app/Http/Controllers/Dashboard/AdminController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Admin;
use Illuminate\Http\Request;
use App\Traits\backendTraits;
use Illuminate\Validation\Rule;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class AdminController extends Controller
{
    use backendTraits;
    // public function __construct()
    // {
    //   $this->middleware(['permission:read_users'])->only('index');

    //   $this->middleware(['permission:create_users'])->only('create');

    //   $this->middleware(['permission:update_users'])->only('edit');

    //   $this->middleware(['permission:delete_users'])->only('destroy');
    // }//end of construct


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
           $data['users'] = Admin::when($request->search , function ($q) use ($request){
              return $q->where('username' , 'like' , '%'. $request->search. '%')
              ->orWhere('first_name' , 'like' , '%'. $request->search. '%')
              ->orWhere('last_name' , 'like' , '%'. $request->search. '%')
              ->orWhere('email' , 'like' , '%'. $request->search. '%');
          })->latest()->get();

          $data['total'] = Admin::count();

        return view('dashboard.users.index')->with($data);
    }


     /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.users.create');
    }


     /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //return $request;
        $request->validate([
            'first_name'  => 'required|string|min:3|max:20',
            'last_name'   => 'required|string|min:3|max:20',
            'username'    => 'required|string|min:3|max:20|unique:admins',
            'email'       => 'nullable|email|unique:admins',
            'image'       => 'nullable',
            'password'    => 'required|confirmed',
            'permissions' => 'required|min:1',
        ],[
            'first_name.required' => __('user.req_first_name'),
            'last_name.required'  => __('user.req_last_name'),
            'username.required'   => __('user.req_username'),
            'username.unique'     => __('user.unique_username'),
            'email.unique'        => __('user.unique_email'),
            'password.required'   => __('user.req_password'),
            'password.confirmed'  => __('user.password_confirmed'),
        ]
        );
            $data = $request->except(['password', 'password_confirmation', 'permissions', 'image']);
            $data['password'] = bcrypt($request->password);

            if ($request->image) {
                $data['image'] = $this->upploadImage($request->image, 'uploads/users_images');
             }else{
                $data['image'] = 'default.png';
             }
            $user = Admin::create($data);

            $user->attachRole('admin');

            $user->syncPermissions($request->permissions);

            session()->flash('success', __('user.added_successfully'));

            return redirect()->route('admin.users.index');
    }

      /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = Admin::find($id);
        return view('dashboard.users.edit' , compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $user = Admin::find($id);
        $request->validate([
            'first_name'  => 'required|string|min:3|max:20',
            'last_name'   => 'required|string|min:3|max:20',
            'username'    => ['required','string','min:3','max:20', Rule::unique('admins')->ignore($user->id)],
            'email'       => ['nullable', Rule::unique('admins')->ignore($user->id)],
            'image'       => 'nullable',
            'permissions' => 'required|min:1',
        ],
        [
            'first_name.required' => __('user.req_first_name'),
            'last_name.required'  => __('user.req_last_name'),
            'username.required'   => __('user.req_username'),
            'username.unique'     => __('user.unique_username'),
            'email.unique'        => __('user.unique_email'),
        ]);
        $data = $request->except(['permissions', 'image']);

        if ($request->image) {
            if ($user->image != 'default.png') {
                $this->deleteFile( pathinfo($user->image)['basename'], 'uploads/users_images/');
                // Storage::disk('uploads')->delete('/users_images/' . $user->image);
            }

            $data['image'] = $this->upploadImage($request->image, 'uploads/users_images');
        }

        $user->update($data);
        $user->syncPermissions($request->permissions);
        session()->flash('success', __('user.updated_successfully'));
        return redirect()->route('admin.users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         $admin = Admin::find($id);
        if ($admin->image != 'default.png') {
            $this->deleteFile( pathinfo($admin->image)['basename'], 'uploads/users_images/');
            // Storage::disk('uploads')->delete('/users_images/' . $admin->image);
        }

        $admin->delete();

        session()->flash('success',  __('user.deleted_successfully'));

        return redirect()->route('admin.users.index');
    }
}

app/Http/Controllers/Dashboard/AdvertisementTypeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\AdvertisementType;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;


class AdvertisementTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $adTypes = AdvertisementType::select('id','name_ar','name_en',
        'name_'.app()->getLocale().' AS name')->get();
        return view('dashboard.advertisement_types.index' , compact('adTypes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name_ar'  => 'required|string|min:3|max:20|unique:advertisement_types',
            'name_en'  => 'required|string|min:3|max:20|unique:advertisement_types',
        ],[
            
        ]
        );
            $data = $request->all();

            AdvertisementType::create($data);

            session()->flash('success', __('user.added_successfully'));

            return redirect()->route('admin.advertisement-types.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $type = AdvertisementType::find($request->id);
        $request->validate([
            'name_ar'  => ['required','string','min:3','max:20', Rule::unique('advertisement_types')->ignore($type->id)],
            'name_en'  => ['required','string','min:3','max:20', Rule::unique('advertisement_types')->ignore($type->id)],
        ],[
            'name_ar.required'    => __('user.reqStatNameAr'),
            'name_ar.unique'      => __('user.uniqueStatNameAr'),
            'name_en.required'    => __('user.reqStatNameEn'),
            'name_en.unique'      => __('user.uniqueStatNameEn'),
        ]);
        $data = $request->except('_token','_method');

        $type->update($data);
        session()->flash('success', __('user.updated_successfully'));
        return redirect()->route('admin.advertisement-types.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $type = AdvertisementType::find($id);
        $type->delete();
        session()->flash('success',  __('user.deleted_successfully'));
        return redirect()->route('admin.advertisement-types.index');
    }
}

app/Http/Controllers/Dashboard/HomeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
     /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('adminauth:admin');
    }

      /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('dashboard.layout.mainlayout');
    }
}

resources/views/dashboard/subscriptions/create.blade.php
<?php $page="admin.subscriptions"?>
@extends('dashboard.layout.mainlayout')
@section('content')
    <!-- Page Wrapper -->
    <div class="page-wrapper">
        <div class="content container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title mb-0">@lang('user.subscription')</h4>
                        </div>
                        @include('partials._errors')
                        @include('partials._session')
                        <div class="card-body">
                            <form action="{{route('admin.subscriptions.store')}}" method="POST" autocomplete="off">
                                @csrf
                                {{-- <h4 class="card-title">@lang('user.add_new_slider')</h4> --}}
                                    <div class="form-row">
                                        <div class="col-md-6 mb-3p">
                                            <label>@lang('user.subscription_name_ar')</label>
                                            <input type="text" name="name_ar" class="form-control" value="{{ old('name_ar') }}" placeholder="@lang('user.subscription_name_ar')" required>
                                        </div>
                                        <div class="col-md-6 mb-3p">
                                            <label>@lang('user.subscription_name_en')</label>
                                            <input type="text" name="name_en" class="form-control" value="{{ old('name_en') }}" placeholder="@lang('user.subscription_name_en')" required>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6 mb-3p">
                                            <label>@lang('user.ads_number')</label>
                                            <input type="number" name="ads_number" class="form-control" value="{{ old('ads_number') }}" placeholder="@lang('user.ads_number')" required>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6 mb-3p">
                                            <label>@lang('user.price')</label>
                                            <input type="number" step="0.01" name="price" class="form-control" value="{{ old('price') }}" placeholder="@lang('user.price')" required>
                                        </div>
                                        <div class="col-md-6 mb-3">
                                            <label>@lang('user.expiration')</label>
                                            <input type="number" step="1" min="0" name="period" class="form-control" value="{{ old('expiration') }}" placeholder="@lang('user.expiration')" required>
                                        </div>
                                    </div>

                                    <div class="form-row">
                                        <div class="col-md-6 mb-4p">
                                            <label>@lang('user.user_type')</label>
                                            {{--  <div class="col-lg-6 col-sm-12 mt-3">  --}}
                                                <select  name="user_type" class="custom-select h-1000 ">
                                                    {{--  <select  name="type" class="custom-select w-100 p-2 rounded">  --}}
                                                    <option value="2" >الكل</option>
                                                    <option value="0" >فرد</option>
                                                    <option value="1" >تاجر</option>
                                                </select>
                                            {{--  </div>  --}}
                                        </div>
                                    </div><br>

                                <div class="text-right">
                                    <button type="submit" class="btn btn-primary">@lang('user.add')</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection




<!-- Modal -->
 {{-- <div class="modal fade" id="add_task" tabindex="-1" role="dialog" aria-modal="true">
    <div class="modal-dialog" role="document">
        <button type="button" class="close md-close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <div class="modal-content">

            <div class="modal-header">
                <h4 class="modal-title text-center">@lang('user.cat_name')</h4>
                <button type="button" class="close xs-close" data-dismiss="modal">×</button>
              </div>

            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <form action="{{route('admin.slider.store')}}" method="POST" autocomplete="off">
                            @csrf

                            <div class="form-group row">
                                <div class="col-sm-6">
                                     <label class="col-form-label">@lang('user.cat_name') <span class="text-danger">*</span></label>
                                    <select name="cat_id" id="" class="form-control">
                                        <option value="" selected disabled>@lang('user.cat_name') </option>
                                        @foreach ($cats as $cat)
                                            <option value="{{$cat->id}}">{{$cat->name}}</option>
                                        @endforeach
                                    </select>
                                </div>

                            </div>
                            <div class="text-center py-3">
                                <button type="submit" class="border-0 btn btn-primary btn-gradient-primary btn-rounded">@lang('user.add')</button>&nbsp;&nbsp;

                            </div>
                        </form>
                    </div>
                </div>

            </div>

        </div>
    </div>
</div> --}}
<!-- modal -->

resources/views/dashboard/subscriptions/index.blade.php
<?php $page="admin.subscriptions";?>
@extends('dashboard.layout.mainlayout')
@section('content')
<!-- Page Wrapper -->
<div class="page-wrapper">
                <div class="content container-fluid">
					<div class="row">
						<div class="col-sm-12">
                            <div class="crms-title row bg-white">
                                    <h3 class="page-title m-0">
                                      @if(Auth::guard('admin')->user()->hasPermission('subscription_create'))
                                        {{-- <button class="add btn btn-gradient-primary font-weight-bold text-white todo-list-add-btn btn-rounded" id="add-task" data-toggle="modal" data-target="#add_task">@lang('user.add')</button> --}}
                                        <a href="{{route('admin.subscriptions.create')}}" class="btn btn-info">@lang('user.add')</a>
                                      {{-- @else
                                        <button class="add btn btn-gradient-primary font-weight-bold text-white todo-list-add-btn btn-rounded" disabled>@lang('user.add')</button> --}}
                                      @endif
                            </div>
							<div class="card mb-0">
								<div class="card-header">
                                    <h3 class="box-title" style="margin-bottom: 10px;">@lang('user.subscription')
                                        <small>{{ $subscriptions->count() }}</small>
                                    </h3>
								</div>

								<div class="card-body">
                                    @include('partials._errors')
                                    @include('partials._session')
									<div class="table-responsive">
                                        @if($subscriptions->count() > 0)
                                            <table class="datatable table table-stripped mb-0 datatables">
                                                <thead>
                                                    <tr>
                                                        <th style="width: 5%" scope="col">#</th>
                                                        <th>@lang('user.name')</th>
                                                        <th>@lang('user.ads_number')</th>
                                                        <th>@lang('user.price')</th>
                                                        <th>@lang('user.expiration')</th>
                                                        <th>@lang('user.user_type')</th>
                                                        <th>@lang('user.operations')</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach ($subscriptions as $index=>$item)
                                                        <tr>
                                                            <th style="width: 5%" scope="row">{{ $index +1 }}</th>
                                                            <td>{{$item->name}}</td>
                                                            <td>{{$item->ads_number}}</td>
                                                            <td>{{$item->price}}</td>
                                                            <td>{{$item->period}}</td>

                                                            <td>{{$item->user_type == '0' ? 'فرد'  :  '' }}
                                                                {{$item->user_type == '1' ? 'تاجر'  :  '' }}
                                                                {{$item->user_type == '2' ? 'الكل'  :  '' }}</td>
                                                            {{--  <td>{{$item->user_type == 0 ? __('user.operations') : @if ($item->user_type == 1) __('user.operations') @else __('user.operations')}}@endif </td>  --}}

                                                            <td>
                                                                @if(Auth::guard('admin')->user()->hasPermission('subscription_update'))
                                                                    <a href="{{route('admin.subscriptions.edit',$item->id)}}" class="btn btn-info btn-sm">@lang('user.edit')</a>
                                                                @else
                                                                    <a href="#" class="btn btn-info btn-sm" disabled>@lang('user.edit')</a>
                                                                @endif

                                                                @if(Auth::guard('admin')->user()->hasPermission('subscription_delete'))
                                                                    <form action="{{route('admin.subscriptions.destroy',$item->id)}}" method="POST"
                                                                        style="display:inline-block">
                                                                        @csrf
                                                                        @method('DELETE')
                                                                        <button type="submit" class="btb btn-danger btn-sm delete">@lang('user.delete')</button>
                                                                    </form> <!--end of form -->
                                                                @else
                                                                    <button type="submit" class="btb btn-danger btn-sm" disabled>@lang('user.delete')</button>
                                                                @endif
                                                            </td>
                                                        </tr>
                                                    @endforeach
                                                </tbody>
                                            </table>
                                        @else
                                            <h2>@lang('user.no_data_found')</h2>
                                        @endif
									</div>
								</div>
							</div>
						</div>
					</div>
                    {{-- @include('dashboard.sliders.create') --}}
				</div>
			</div>
			<!-- /Page Wrapper -->

        </div>
		<!-- /Main Wrapper -->
<!--theme settings modal-->
@endsection
@section('scripts')
<script>
    //Edit Catgeoy
    $('#edit_task').on('show.bs.modal', function(event) {
        var button = $(event.relatedTarget)
        var id = button.data('id')
        var name_ar = button.data('country_ar')
        var name_en = button.data('country_en')
        var modal = $(this)
        modal.find('.modal-body #country_id').val(id);
        modal.find('.modal-body #country-AR').val(name_ar);
        modal.find('.modal-body #country-EN').val(name_en);
    })
</script>
@endsection