routes/web.php
<?php

use App\Http\Controllers\Dashboard\NotificationController;
use App\Models\Advertisement;
use App\Models\Attribute;
use App\Models\Cart;
use App\Models\Category;
use App\Models\Chat;
use App\Models\Desire;
use App\Models\Order;
use App\Models\Subattribute;
use Carbon\Carbon;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Login to Dashboard
// Route::get('/', 'Dashboard\AuthController@index')->name('home');


Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']], function () {

    //IF Admin Not Auth Return to login
    // Route::get('/dashboard', function () {
    //     return view('dashboard.index');
    // })->name('pagee')->middleware('adminauth:admin');

    // Website routes
    // Route::group(['namespace' => 'Site'], function () {
    //     Route::get('/', 'SiteController@index');
    // });



    // Clear application cache:
    Route::get('/clear-cache', function() {
        \Artisan::call('optimize:clear');
            // \Artisan::call('cache:clear');
        return 'Application cache has been cleared';
    });

    //site route
    //Route::get('/', 'Site\SiteController@index');
    Route::get('/',function(){
        return '404 Not Found!';
    });

    // Dashboard routes
    Route::group(['prefix' => 'dashboard', 'namespace' => 'Dashboard'], function () {
        Route::get('/', 'DashboardController@index')->name('pagee')->middleware('adminauth:admin');
        //Login process
        Route::get('/login', 'AuthController@login')->name('admin.login');
        Route::post('/do-login', 'AuthController@doLogin')->name('admin.doLogin');

        Route::name('admin.')->middleware('adminauth:admin')->group(function () {
            //Logout proccess
            Route::get('/logout', 'AuthController@logout')->name('logout');

            //Admin Routes
            Route::resource('users', 'AdminController')->except(['show']);

            // Profile
            Route::get('profile', 'ProfileController@profile')->name('profiles');
            Route::get('profile/edit', 'ProfileController@editProfile')->name('profiles.edit');
            Route::put('profile/update', 'ProfileController@updateProfile')->name('profiles.update');
            Route::get('profile/change_password', 'ProfileController@changePassword')->name('profiles.change_password');
            Route::put('profile/change_password', 'ProfileController@change_password_method')->name('profiles.change_password_method');

            //Customers routes
            Route::resource('customer', 'CustomersController');
            Route::get('customer-excel', 'CustomersController@customersPrintExcel')->name('customer.index.excel');


            //Merchant routes
            Route::resource('merchant', 'MerchantController');
            // Route::get('merchant/active/{id}', 'MerchantController@changeStatus')->name('merchant.active');addComments
            Route::post('merchant/addComments', 'MerchantController@addComments')->name('merchant.addComments');
            Route::get('merchant/active/{id}', 'MerchantController@changeStatus')->name('merchant.active');
            Route::get('merchant/dependence/{id}', 'MerchantController@changeDependence')->name('merchant.dependence');
            Route::get('merchant/changeViewRate/{id}', 'MerchantController@changeViewRate')->name('merchant.changeViewRate');
            Route::get('merchant-excel', 'MerchantController@merchantsPrintExcel')->name('merchant.index.excel');


            // Country routes
            Route::resource('countries', CountryController::class);

            // Governorates routes
            Route::resource('countries/{country}/governorates', GovernorateController::class);

            // districts routes
            Route::resource('countries/{country}/governorates/{governorate}/districts', DistrictController::class);

            // Categories routes
            Route::resource('categories', CategoryController::class);

            //Subcategories routes
            Route::resource('categories/{cat}/subcategories', SubcategoryController::class);

            // Attributes routes
            Route::resource('categories/{cat}/subcategories/{subcat}/attributes', AttributeController::class);
            Route::post('categories/{cat}/subcategories/{subcat}/attributes/save', 'AttributeController@createSub')->name('subattributes.save');
            Route::post('categories/{cat}/subcategories/{subcat}/attributes/delete/{id}', 'AttributeController@deleteSub')->name('subattributes.delete');

            //Advertisements
            Route::resource('advertisements', AdvertisementController::class);
            Route::get('fees-expiration' , 'AdvertisementController@getFeesExpiration')->name('fees-expiration.index');
            Route::get('advertisements/popular/{id}', 'AdvertisementController@changeStatusPopular')->name('advertisements.popular');

            Route::post('advertisements/fees-expiration' , 'AdvertisementController@updateFeesExpiration')->name('fees-expiration.update');
            Route::resource('advertisement-types' , AdvertisementTypeController::class);

            //special advertisements
            Route::resource('special-advertisements' , SpecialAdvertisementController::class);

            //Subscriptions
            Route::resource('subscriptions', SubscriptionController::class);

            //Funds
            Route::get('financing_request', 'FundController@financingRequest')->name('financing_request');
            Route::resource('funds', FundController::class);


            Route::get('report', 'SettingController@report')->name('report.index');
            Route::get('report-excel', 'SettingController@reportPrintExcel')->name('report.index.excel');

            // Setting
            Route::resource('slider', 'SliderController');
            Route::post('ajaxLoad', 'SliderController@ajaxLoad')->name('ajaxLoad');

            Route::get('feedbacks','SettingController@feedback')->name('setting.feedback');
            Route::get('form_contact_us','SettingController@formContactUs')->name('setting.form_contact_us');

            Route::get('setting/banner', 'SettingController@banner')->name('setting.banner');
            Route::put('setting/banner/{id}/update', 'SettingController@editBanner')->name('setting.banner.update');

            Route::get('setting/banner/{id}/delete', 'SettingController@deleteBanner')->name('setting.banner.delete');

            Route::get('setting/contact-us', 'SettingController@contactUs')->name('setting.contact-us');
            Route::put('setting/contact-us/{id}/update', 'SettingController@editContactUs')->name('setting.contact-us.update');

            Route::get('setting/terms', 'SettingController@terms')->name('setting.terms');
            Route::put('setting/terms/{id}/update', 'SettingController@editTerms')->name('setting.terms.update');

            Route::get('setting/about', 'SettingController@about')->name('setting.about');
            Route::put('setting/about/{id}/update', 'SettingController@editAbout')->name('setting.about.update');

            Route::get('setting/delivery-tax', 'SettingController@deliveryCostAndTax')->name('setting.delivery-tax');
            Route::post('setting/delivery-tax', 'SettingController@updateDeliveryCostAndTax')->name('setting.delivery-tax.update');

            //Notifications
            Route::get('notifications','NotificationController@index')->name('notifications.index');
            Route::post('notifications','NotificationController@send')->name('notifications.send');

            //coupons
            Route::resource('coupons','CouponController');
        });
    });
});
Route::get('test', function () {

});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'categories';
    protected $guarded = [];

    public function  getImagePathAttribute()
    {
      return asset('uploads/categories/'. $this->image);
    }// end of get Image Path

    public function  getIconPathAttribute()
    {
      return asset('uploads/categories/'. $this->icon);
    }// end of get icon Path

    public function subcategories(){
      return $this->hasMany(Subcategory::class , 'cat_id');
    }

    public function SpecialAdvertisement(){
        return $this->hasMany(SpecialAdvertisement::class , 'cat_id');
    }

} // end of Category

app/Http/Controllers/Dashboard/AdminController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Admin;
use Illuminate\Http\Request;
use App\Traits\backendTraits;
use Illuminate\Validation\Rule;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class AdminController extends Controller
{
    use backendTraits;
    // public function __construct()
    // {
    //   $this->middleware(['permission:read_users'])->only('index');

    //   $this->middleware(['permission:create_users'])->only('create');

    //   $this->middleware(['permission:update_users'])->only('edit');

    //   $this->middleware(['permission:delete_users'])->only('destroy');
    // }//end of construct


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
           $data['users'] = Admin::when($request->search , function ($q) use ($request){
              return $q->where('username' , 'like' , '%'. $request->search. '%')
              ->orWhere('first_name' , 'like' , '%'. $request->search. '%')
              ->orWhere('last_name' , 'like' , '%'. $request->search. '%')
              ->orWhere('email' , 'like' , '%'. $request->search. '%');
          })->latest()->get();

          $data['total'] = Admin::count();

        return view('dashboard.users.index')->with($data);
    }


     /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.users.create');
    }


     /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //return $request;
        $request->validate([
            'first_name'  => 'required|string|min:3|max:20',
            'last_name'   => 'required|string|min:3|max:20',
            'username'    => 'required|string|min:3|max:20|unique:admins',
            'email'       => 'nullable|email|unique:admins',
            'image'       => 'nullable',
            'password'    => 'required|confirmed',
            'permissions' => 'required|min:1',
        ],[
            'first_name.required' => __('user.req_first_name'),
            'last_name.required'  => __('user.req_last_name'),
            'username.required'   => __('user.req_username'),
            'username.unique'     => __('user.unique_username'),
            'email.unique'        => __('user.unique_email'),
            'password.required'   => __('user.req_password'),
            'password.confirmed'  => __('user.password_confirmed'),
        ]
        );
            $data = $request->except(['password', 'password_confirmation', 'permissions', 'image']);
            $data['password'] = bcrypt($request->password);

            if ($request->image) {
                $data['image'] = $this->upploadImage($request->image, 'uploads/users_images');
             }else{
                $data['image'] = 'default.png';
             }
            $user = Admin::create($data);

            $user->attachRole('admin');

            $user->syncPermissions($request->permissions);

            session()->flash('success', __('user.added_successfully'));

            return redirect()->route('admin.users.index');
    }

      /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = Admin::find($id);
        return view('dashboard.users.edit' , compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $user = Admin::find($id);
        $request->validate([
            'first_name'  => 'required|string|min:3|max:20',
            'last_name'   => 'required|string|min:3|max:20',
            'username'    => ['required','string','min:3','max:20', Rule::unique('admins')->ignore($user->id)],
            'email'       => ['nullable', Rule::unique('admins')->ignore($user->id)],
            'image'       => 'nullable',
            'permissions' => 'required|min:1',
        ],
        [
            'first_name.required' => __('user.req_first_name'),
            'last_name.required'  => __('user.req_last_name'),
            'username.required'   => __('user.req_username'),
            'username.unique'     => __('user.unique_username'),
            'email.unique'        => __('user.unique_email'),
        ]);
        $data = $request->except(['permissions', 'image']);

        if ($request->image) {
            if ($user->image != 'default.png') {
                $this->deleteFile( pathinfo($user->image)['basename'], 'uploads/users_images/');
                // Storage::disk('uploads')->delete('/users_images/' . $user->image);
            }

            $data['image'] = $this->upploadImage($request->image, 'uploads/users_images');
        }

        $user->update($data);
        $user->syncPermissions($request->permissions);
        session()->flash('success', __('user.updated_successfully'));
        return redirect()->route('admin.users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         $admin = Admin::find($id);
        if ($admin->image != 'default.png') {
            $this->deleteFile( pathinfo($admin->image)['basename'], 'uploads/users_images/');
            // Storage::disk('uploads')->delete('/users_images/' . $admin->image);
        }

        $admin->delete();

        session()->flash('success',  __('user.deleted_successfully'));

        return redirect()->route('admin.users.index');
    }
}

app/Http/Controllers/Dashboard/AuthController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Redirect;

class AuthController extends Controller
{
    /**
     * Return to login blade
     */
    public function login()
    {
        return view('dashboard.auth.login');
    }


    /**
     * Login Function
     */
    public function doLogin(Request $request)
    {
        $data = $request->validate([
            'username' => 'required|string|max:191',
            'password' => 'required|string'
        ]);

        // $new_pass = bcrypt($data['password']);

        if(!auth()->guard('admin')->attempt(['username' => $data['username'] , 'password' => $data['password']]))
        {
            // dd($data);
            // return Redirect::back()->withErrors(['Try With Correct Email and Password!!']);
            session()->flash('error', __("user.error_credentials"));
            return redirect()->back();
        }
            session()->flash('success', __('user.succes_login'));
            return redirect(route('pagee'));
    }

    /**
     * Logout Function
     */

    public function logout()
    {
        auth()->guard('admin')->logout();
        return redirect(route('admin.login'));
    }

}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Admin;
use App\Models\Advertisement;
use App\Models\Category;
use App\Models\Country;
use App\Models\Subscription;
use App\Models\User;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index(){
        $data['user']  = User::where('type', 0)->count();
        $data['merchant']  = User::where('type', 1)->count();
        $data['admin'] = Admin::count();
        $data['country']         = Country::count();
        $data['category']       = Category::count();
        $data['subscription']       = Subscription::count();
        $data['advertisements'] = Advertisement::count();

        return view('dashboard.index')->with($data);
    }// end of index
}

app/Http/Controllers/Dashboard/HomeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
     /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('adminauth:admin');
    }

      /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('dashboard.layout.mainlayout');
    }
}

resources/views/dashboard/categories/edit.blade.php
<?php $page="admin.categories";?>
@extends('dashboard.layout.mainlayout')
@section('content')
    <!-- Page Wrapper -->
    <div class="page-wrapper">
        <div class="content container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title mb-0">@lang('user.user')</h4>
                        </div>
                        @include('partials._errors')
                        @include('partials._session')
                        <div class="card-body">
                            <form action="{{route('admin.categories.update',$category->id)}}" method="POST" autocomplete="off" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <h4 class="card-title">@lang('user.addNewCat')</h4>
                                    <div class="form-row">
                                        <div class="col-md-6 mb-3">
                                            <input type="hidden" name="id" value="{{$category->id}}">
                                            <label>@lang('user.catAr')</label>
                                            <input type="text" name="name_ar" class="form-control" value="{{$category->name_ar}}" placeholder="@lang('user.catAr')" required>
                                        </div>
                                        <div class="col-md-6 mb-3">
                                            <label>@lang('user.catEn')</label>
                                            <input type="text" class="form-control" name="name_en" value="{{$category->name_en}}" placeholder="@lang('user.catEn')" required>
                                        </div>
                                    </div>

                                    <div class="form-row">
                                        <div class="col-md-6 mb-3">
                                            <label>@lang('user.type_name_ar')</label>
                                            <input type="text" name="type_name_ar" class="form-control" value="{{$category->type_name_ar}}" placeholder="@lang('user.type_name_ar')" required>
                                        </div>
                                        <div class="col-md-6 mb-3">
                                            <label>@lang('user.type_name_en')</label>
                                            <input type="text" class="form-control" name="type_name_en" value="{{$category->type_name_en}}" placeholder="@lang('user.type_name_en')" required>
                                        </div>
                                    </div>

                                    <div class="form-row">
                                        <div class="col-md-6 mb-3">
                                            <label>@lang('user.details_name_ar')</label>
                                            <input type="text" name="details_name_ar" class="form-control" value="{{ $category->details_name_ar }}" placeholder="@lang('user.details_name_ar')" required>
                                        </div>
                                        <div class="col-md-6 mb-3">
                                            <label>@lang('user.details_name_en')</label>
                                            <input type="text" class="form-control" name="details_name_en" value="{{ $category->details_name_en }}" placeholder="@lang('user.details_name_en')" required>
                                        </div>
                                    </div>

                                    <div class="form-row">
                                        <div class="col-md-6 mb-3">
                                            <label>@lang('user.sorting')</label>
                                            <input type="number" name="sorting" class="form-control" value="{{ $category->sorting }}" placeholder="@lang('user.sorting')" required>
                                        </div>
                                    </div>

                                    <div class="form-row">
                                        <div class="col-md-6 mb-3p">
                                            <label>@lang('user.icon')</label>
                                            <input type="file" name="icon" class="form-control" >
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6 mb-3">
                                            <img src="{{$category->icon_path }}"
                                                class="img-thumbnail" style="width: 100px;">
                                        </div>
                                    </div>

                                    <div class="form-row">
                                        <div class="col-md-6 mb-3p">
                                            <label>@lang('user.image')</label>
                                            <input type="file" name="image" class="form-control image" >
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6 mb-3">
                                            <img src="{{$category->image_path }}"
                                                class="img-thumbnail image-preview" style="width: 100px;">
                                        </div>
                                    </div>
                                <div class="text-right">
                                    <button type="submit" class="btn btn-primary">@lang('user.add')</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/categories/index.blade.php
<?php $page="admin.categories";?>
@extends('dashboard.layout.mainlayout')
@section('content')
<!-- Page Wrapper -->
<div class="page-wrapper">
                <div class="content container-fluid">
					<div class="row">
						<div class="col-sm-12">
							<div class="card mb-0">
								<div class="card-header">
                                    <h3 class="box-title" style="margin-bottom: 10px;">@lang('user.cats')
                                        <small>{{ $total }}</small>
                                    </h3>
									<p class="card-text">
                                        <form action="{{route('admin.categories.index')}}" method="get">
                                            <div class="row">
                                                <div class="col-md-2">
                                                    <input type="text" name="search" class="form-control" value="{{ request()->search }}"
                                                           placeholder="@lang('user.search')">
                                                </div>
                                                <div class="col-md-4">
                                                    <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i>@lang('user.search')</button>
                                                    @if(Auth::guard('admin')->user()->hasPermission('cats_create'))
                                                        <a href="{{route('admin.categories.create')}}" class="btn btn-primary"><i class="fa fa-plus"></i>@lang('user.add')</a>
                                                    @else
                                                        <a href="#" class="btn btn-primary" disabled><i class="fa fa-plus"></i>@lang('user.add')</a>
                                                    @endif
                                                </div>
                                            </div>
                                        </form>
                                    </p>
								</div>


								<div class="card-body">

									<div class="table-responsive">
										<table class="datatable table table-stripped mb-0 datatables">
											<thead>
												<tr>
                                                    <th>#</th>
                                                    <th>@lang('user.cat_name')</th>
                                                    <th>@lang('user.sorting')</th>
                                                    <th>@lang('user.type_name')</th>
                                                    <th>@lang('user.details_name')</th>
													<th>@lang('user.image')</th>
                                                    <th>@lang('user.icon')</th>
													<th>@lang('user.operations')</th>
												</tr>
											</thead>
											<tbody>
                                                @foreach ($cats as $index => $item)
                                                    <tr>
                                                        <td>{{$index + 1}}</td>
                                                        <td>
                                                            {{$item->name}}
                                                        </td>
                                                        <td>
                                                            {{$item->sorting}}
                                                        </td>
                                                        <td>
                                                            {{$item->type_name}}
                                                        </td>
                                                        <td>
                                                            {{$item->details_name}}
                                                        </td>
                                                        <td>
                                                            <img src="{{ $item->image_path }}" style="width:50px" class="img-thumbnail" alt="">
                                                        </td>
                                                        <td>
                                                            <img src="{{ $item->icon_path }}" style="width:50px" class="img-thumbnail" alt="">
                                                        </td>
                                                        <td>
                                                            @if(Auth::guard('admin')->user()->hasPermission('subcats_read'))
                                                                <a href="{{route('admin.subcategories.index',['cat'=>$item->id])}}" class="btn btn-primary btn-sm">@lang('user.subcats')</a>
                                                            @else
                                                                <a href="#" class="btn btn-primary btn-sm" disabled>@lang('user.subcats')</a>
                                                            @endif

                                                            @if(Auth::guard('admin')->user()->hasPermission('cats_update'))
                                                                <a href="{{route('admin.categories.edit',$item->id)}}" class="btn btn-info btn-sm">@lang('user.edit')</a>
                                                            @else
                                                                <a href="#" class="btn btn-info btn-sm" disabled>@lang('user.edit')</a>
                                                            @endif

                                                            @if(Auth::guard('admin')->user()->hasPermission('cats_delete'))
                                                                <form action="{{route('admin.categories.destroy',$item->id)}}" method="POST"
                                                                    style="display:inline-block">
                                                                    @csrf
                                                                    @method('DELETE')
                                                                    <button type="submit" class="btb btn-danger btn-sm delete">@lang('user.delete')</button>
                                                                </form> <!--end of form -->
                                                            @else
                                                                <button type="submit" class="btb btn-danger btn-sm" disabled>@lang('user.delete')</button>
                                                            @endif
                                                        </td>
                                                    </tr>
                                                @endforeach
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>

				</div>
			</div>
			<!-- /Page Wrapper -->

        </div>
		<!-- /Main Wrapper -->
<!--theme settings modal-->
@endsection