routes/web.php
<?php

use App\Http\Controllers\Dashboard\NotificationController;
use App\Models\Advertisement;
use App\Models\Attribute;
use App\Models\Cart;
use App\Models\Category;
use App\Models\Chat;
use App\Models\Desire;
use App\Models\Order;
use App\Models\Subattribute;
use Carbon\Carbon;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Login to Dashboard
// Route::get('/', 'Dashboard\AuthController@index')->name('home');


Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']], function () {

    //IF Admin Not Auth Return to login
    // Route::get('/dashboard', function () {
    //     return view('dashboard.index');
    // })->name('pagee')->middleware('adminauth:admin');

    // Website routes
    // Route::group(['namespace' => 'Site'], function () {
    //     Route::get('/', 'SiteController@index');
    // });



    // Clear application cache:
    Route::get('/clear-cache', function() {
        \Artisan::call('optimize:clear');
            // \Artisan::call('cache:clear');
        return 'Application cache has been cleared';
    });

    //site route
    //Route::get('/', 'Site\SiteController@index');
    Route::get('/',function(){
        return '404 Not Found!';
    });

    // Dashboard routes
    Route::group(['prefix' => 'dashboard', 'namespace' => 'Dashboard'], function () {
        Route::get('/', 'DashboardController@index')->name('pagee')->middleware('adminauth:admin');
        //Login process
        Route::get('/login', 'AuthController@login')->name('admin.login');
        Route::post('/do-login', 'AuthController@doLogin')->name('admin.doLogin');

        Route::name('admin.')->middleware('adminauth:admin')->group(function () {
            //Logout proccess
            Route::get('/logout', 'AuthController@logout')->name('logout');

            //Admin Routes
            Route::resource('users', 'AdminController')->except(['show']);

            // Profile
            Route::get('profile', 'ProfileController@profile')->name('profiles');
            Route::get('profile/edit', 'ProfileController@editProfile')->name('profiles.edit');
            Route::put('profile/update', 'ProfileController@updateProfile')->name('profiles.update');
            Route::get('profile/change_password', 'ProfileController@changePassword')->name('profiles.change_password');
            Route::put('profile/change_password', 'ProfileController@change_password_method')->name('profiles.change_password_method');

            //Customers routes
            Route::resource('customer', 'CustomersController');
            Route::get('customer-excel', 'CustomersController@customersPrintExcel')->name('customer.index.excel');


            //Merchant routes
            Route::resource('merchant', 'MerchantController');
            // Route::get('merchant/active/{id}', 'MerchantController@changeStatus')->name('merchant.active');addComments
            Route::post('merchant/addComments', 'MerchantController@addComments')->name('merchant.addComments');
            Route::get('merchant/active/{id}', 'MerchantController@changeStatus')->name('merchant.active');
            Route::get('merchant/dependence/{id}', 'MerchantController@changeDependence')->name('merchant.dependence');
            Route::get('merchant/changeViewRate/{id}', 'MerchantController@changeViewRate')->name('merchant.changeViewRate');
            Route::get('merchant-excel', 'MerchantController@merchantsPrintExcel')->name('merchant.index.excel');


            // Country routes
            Route::resource('countries', CountryController::class);

            // Governorates routes
            Route::resource('countries/{country}/governorates', GovernorateController::class);

            // districts routes
            Route::resource('countries/{country}/governorates/{governorate}/districts', DistrictController::class);

            // Categories routes
            Route::resource('categories', CategoryController::class);

            //Subcategories routes
            Route::resource('categories/{cat}/subcategories', SubcategoryController::class);

            // Attributes routes
            Route::resource('categories/{cat}/subcategories/{subcat}/attributes', AttributeController::class);
            Route::post('categories/{cat}/subcategories/{subcat}/attributes/save', 'AttributeController@createSub')->name('subattributes.save');
            Route::post('categories/{cat}/subcategories/{subcat}/attributes/delete/{id}', 'AttributeController@deleteSub')->name('subattributes.delete');

            //Advertisements
            Route::resource('advertisements', AdvertisementController::class);
            Route::get('fees-expiration' , 'AdvertisementController@getFeesExpiration')->name('fees-expiration.index');
            Route::get('advertisements/popular/{id}', 'AdvertisementController@changeStatusPopular')->name('advertisements.popular');

            Route::post('advertisements/fees-expiration' , 'AdvertisementController@updateFeesExpiration')->name('fees-expiration.update');
            Route::resource('advertisement-types' , AdvertisementTypeController::class);

            //special advertisements
            Route::resource('special-advertisements' , SpecialAdvertisementController::class);

            //Subscriptions
            Route::resource('subscriptions', SubscriptionController::class);

            //Funds
            Route::get('financing_request', 'FundController@financingRequest')->name('financing_request');
            Route::resource('funds', FundController::class);


            Route::get('report', 'SettingController@report')->name('report.index');
            Route::get('report-excel', 'SettingController@reportPrintExcel')->name('report.index.excel');

            // Setting
            Route::resource('slider', 'SliderController');
            Route::post('ajaxLoad', 'SliderController@ajaxLoad')->name('ajaxLoad');

            Route::get('feedbacks','SettingController@feedback')->name('setting.feedback');
            Route::get('form_contact_us','SettingController@formContactUs')->name('setting.form_contact_us');

            Route::get('setting/banner', 'SettingController@banner')->name('setting.banner');
            Route::put('setting/banner/{id}/update', 'SettingController@editBanner')->name('setting.banner.update');

            Route::get('setting/banner/{id}/delete', 'SettingController@deleteBanner')->name('setting.banner.delete');

            Route::get('setting/contact-us', 'SettingController@contactUs')->name('setting.contact-us');
            Route::put('setting/contact-us/{id}/update', 'SettingController@editContactUs')->name('setting.contact-us.update');

            Route::get('setting/terms', 'SettingController@terms')->name('setting.terms');
            Route::put('setting/terms/{id}/update', 'SettingController@editTerms')->name('setting.terms.update');

            Route::get('setting/about', 'SettingController@about')->name('setting.about');
            Route::put('setting/about/{id}/update', 'SettingController@editAbout')->name('setting.about.update');

            Route::get('setting/delivery-tax', 'SettingController@deliveryCostAndTax')->name('setting.delivery-tax');
            Route::post('setting/delivery-tax', 'SettingController@updateDeliveryCostAndTax')->name('setting.delivery-tax.update');

            //Notifications
            Route::get('notifications','NotificationController@index')->name('notifications.index');
            Route::post('notifications','NotificationController@send')->name('notifications.send');

            //coupons
            Route::resource('coupons','CouponController');
        });
    });
});
Route::get('test', function () {

});

app/Http/Controllers/Dashboard/AdminController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Admin;
use Illuminate\Http\Request;
use App\Traits\backendTraits;
use Illuminate\Validation\Rule;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class AdminController extends Controller
{
    use backendTraits;
    // public function __construct()
    // {
    //   $this->middleware(['permission:read_users'])->only('index');

    //   $this->middleware(['permission:create_users'])->only('create');

    //   $this->middleware(['permission:update_users'])->only('edit');

    //   $this->middleware(['permission:delete_users'])->only('destroy');
    // }//end of construct


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
           $data['users'] = Admin::when($request->search , function ($q) use ($request){
              return $q->where('username' , 'like' , '%'. $request->search. '%')
              ->orWhere('first_name' , 'like' , '%'. $request->search. '%')
              ->orWhere('last_name' , 'like' , '%'. $request->search. '%')
              ->orWhere('email' , 'like' , '%'. $request->search. '%');
          })->latest()->get();

          $data['total'] = Admin::count();

        return view('dashboard.users.index')->with($data);
    }


     /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.users.create');
    }


     /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //return $request;
        $request->validate([
            'first_name'  => 'required|string|min:3|max:20',
            'last_name'   => 'required|string|min:3|max:20',
            'username'    => 'required|string|min:3|max:20|unique:admins',
            'email'       => 'nullable|email|unique:admins',
            'image'       => 'nullable',
            'password'    => 'required|confirmed',
            'permissions' => 'required|min:1',
        ],[
            'first_name.required' => __('user.req_first_name'),
            'last_name.required'  => __('user.req_last_name'),
            'username.required'   => __('user.req_username'),
            'username.unique'     => __('user.unique_username'),
            'email.unique'        => __('user.unique_email'),
            'password.required'   => __('user.req_password'),
            'password.confirmed'  => __('user.password_confirmed'),
        ]
        );
            $data = $request->except(['password', 'password_confirmation', 'permissions', 'image']);
            $data['password'] = bcrypt($request->password);

            if ($request->image) {
                $data['image'] = $this->upploadImage($request->image, 'uploads/users_images');
             }else{
                $data['image'] = 'default.png';
             }
            $user = Admin::create($data);

            $user->attachRole('admin');

            $user->syncPermissions($request->permissions);

            session()->flash('success', __('user.added_successfully'));

            return redirect()->route('admin.users.index');
    }

      /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = Admin::find($id);
        return view('dashboard.users.edit' , compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $user = Admin::find($id);
        $request->validate([
            'first_name'  => 'required|string|min:3|max:20',
            'last_name'   => 'required|string|min:3|max:20',
            'username'    => ['required','string','min:3','max:20', Rule::unique('admins')->ignore($user->id)],
            'email'       => ['nullable', Rule::unique('admins')->ignore($user->id)],
            'image'       => 'nullable',
            'permissions' => 'required|min:1',
        ],
        [
            'first_name.required' => __('user.req_first_name'),
            'last_name.required'  => __('user.req_last_name'),
            'username.required'   => __('user.req_username'),
            'username.unique'     => __('user.unique_username'),
            'email.unique'        => __('user.unique_email'),
        ]);
        $data = $request->except(['permissions', 'image']);

        if ($request->image) {
            if ($user->image != 'default.png') {
                $this->deleteFile( pathinfo($user->image)['basename'], 'uploads/users_images/');
                // Storage::disk('uploads')->delete('/users_images/' . $user->image);
            }

            $data['image'] = $this->upploadImage($request->image, 'uploads/users_images');
        }

        $user->update($data);
        $user->syncPermissions($request->permissions);
        session()->flash('success', __('user.updated_successfully'));
        return redirect()->route('admin.users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         $admin = Admin::find($id);
        if ($admin->image != 'default.png') {
            $this->deleteFile( pathinfo($admin->image)['basename'], 'uploads/users_images/');
            // Storage::disk('uploads')->delete('/users_images/' . $admin->image);
        }

        $admin->delete();

        session()->flash('success',  __('user.deleted_successfully'));

        return redirect()->route('admin.users.index');
    }
}

app/Http/Controllers/Dashboard/AdvertisementTypeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\AdvertisementType;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;


class AdvertisementTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $adTypes = AdvertisementType::select('id','name_ar','name_en',
        'name_'.app()->getLocale().' AS name')->get();
        return view('dashboard.advertisement_types.index' , compact('adTypes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name_ar'  => 'required|string|min:3|max:20|unique:advertisement_types',
            'name_en'  => 'required|string|min:3|max:20|unique:advertisement_types',
        ],[
            
        ]
        );
            $data = $request->all();

            AdvertisementType::create($data);

            session()->flash('success', __('user.added_successfully'));

            return redirect()->route('admin.advertisement-types.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $type = AdvertisementType::find($request->id);
        $request->validate([
            'name_ar'  => ['required','string','min:3','max:20', Rule::unique('advertisement_types')->ignore($type->id)],
            'name_en'  => ['required','string','min:3','max:20', Rule::unique('advertisement_types')->ignore($type->id)],
        ],[
            'name_ar.required'    => __('user.reqStatNameAr'),
            'name_ar.unique'      => __('user.uniqueStatNameAr'),
            'name_en.required'    => __('user.reqStatNameEn'),
            'name_en.unique'      => __('user.uniqueStatNameEn'),
        ]);
        $data = $request->except('_token','_method');

        $type->update($data);
        session()->flash('success', __('user.updated_successfully'));
        return redirect()->route('admin.advertisement-types.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $type = AdvertisementType::find($id);
        $type->delete();
        session()->flash('success',  __('user.deleted_successfully'));
        return redirect()->route('admin.advertisement-types.index');
    }
}

app/Http/Controllers/Dashboard/HomeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
     /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('adminauth:admin');
    }

      /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('dashboard.layout.mainlayout');
    }
}

resources/views/dashboard/advertisements/index.blade.php
<?php $page="admin.advertisements";?>
@extends('dashboard.layout.mainlayout')
@section('content')
<!-- Page Wrapper -->
<div class="page-wrapper">
                <div class="content container-fluid">
					<div class="row">
						<div class="col-sm-12">
							<div class="card mb-0">
								<div class="card-header">
									<h4 class="card-title mb-0">@lang('user.advertisements')</h4>
									<p class="card-text">
                                        <form action="{{route('admin.advertisements.index')}}" method="get">
                                            <div class="row">
                                                <div class="col-md-2">
                                                    <input type="text" name="search" class="form-control" value="{{ request()->search }}"
                                                           placeholder="@lang('user.search')">
                                                </div>
                                            </div>
                                        </form>
                                    </p>
								</div>


								<div class="card-body">

									<div class="table-responsive">
										<table class="datatable table table-stripped mb-0 datatables">
											<thead>
												<tr>
                                                    <th>#</th>
                                                    <th>@lang('user.name')</th>
                                                    <th>@lang('user.subcat_name')</th>
                                                    <th>@lang('user.status')</th>
                                                    <th>@lang('user.address')</th>
                                                    <th>@lang('user.start_date')</th>
													<th>@lang('user.end_date')</th>
													<th>@lang('user.operations')</th>
												</tr>
											</thead>
											<tbody>
                                                @foreach ($advertisements as $index=>$item)
                                                    <tr>
                                                        <td>{{$item->id}}</td>
                                                        <td>
                                                            {{$item->title}}
                                                        </td>
                                                        @if(isset($item->Subcategory))
                                                        @if (App::isLocale('en'))
                                                            <td>
                                                                {{$item->Subcategory->name_en?? '-------'}}
                                                            </td>
                                                        @else
                                                            <td>
                                                                
                                                                
                                                                {{$item->Subcategory->name_ar?? '------'}}
                                                            </td>
                                                        @endif
                                                        @else
                                                         <td>
                                                                
                                                                
                                                                ___
                                                            </td>
                                                        @endif
                                                        <td>
                                                            {{$item->finished==1?__("user.finished"): __("user.current")}}
                                                        </td>
                                                        <td>{{$item->address}}</td>
                                                        <td>
                                                            {{$item->start_date}}
                                                        </td>
                                                        <td>
                                                            {{$item->end_date}}
                                                        </td>
                                                        <td>
                                                            @if(Auth::guard('admin')->user()->hasPermission('advertisement_read'))
                                                            {{--  <a href="{{route('admin.subcategories.index',['cat'=>$item->id])}}" class="btn btn-primary btn-sm">@lang('user.subcats')</a>  --}}
                                                            @if($item->popular == '1')
                                                                <a href="{{route('admin.advertisements.popular', ['id'=> $item->id])}}"
                                                                        class="btn btn-outline-danger box-shadow-3 mr-1 ">@lang('user.delete_popular')</a>
                                                            @else
                                                                <a href="{{route('admin.advertisements.popular', ['id'=> $item->id])}}"
                                                                        class="btn btn-outline-primary box-shadow-3 mr-1 ">@lang('user.add_popular')</a>
                                                            @endif


                                                            <a href="{{route('admin.advertisements.show',$item->id)}}" class="btn btn-info btn-sm">@lang('user.show')</a>
                                                            @else
                                                                <a href="#" class="btn btn-info btn-sm" disabled>@lang('user.show')</a>
                                                            @endif

                                                            @if(Auth::guard('admin')->user()->hasPermission('advertisement_delete'))
                                                                <form action="{{route('admin.advertisements.destroy',$item->id)}}" method="POST"
                                                                    style="display:inline-block">
                                                                    @csrf
                                                                    @method('DELETE')
                                                                    <button type="submit" class="btb btn-danger btn-sm delete">@lang('user.delete')</button>
                                                                </form> <!--end of form -->
                                                            @else
                                                                <button type="submit" class="btb btn-danger btn-sm" disabled>@lang('user.delete')</button>
                                                            @endif
                                                        </td>
                                                    </tr>
                                                @endforeach
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>

				</div>
			</div>
			<!-- /Page Wrapper -->

        </div>
		<!-- /Main Wrapper -->
<!--theme settings modal-->
@endsection